---
version: "3.7"
services:
  hass-screenshot:
    image: zaampie/hass-dashboard-screenshot:latest
    container_name: hass-screenshot
    environment:
      - TZ=Africa/Johannesburg
      - HA_BASE_URL=$HA_BASE_URL
      - HA_ACCESS_TOKEN=$HA_ACCESS_TOKEN
      - LANGUAGE=en
      - REAL_TIME=true
      - RENDERING_DELAY=500
      - HA_SCREENSHOT_URL=$HA_SCREENSHOT_URL
      - RENDERING_SCREEN_HEIGHT=480
      - RENDERING_SCREEN_WIDTH=800
      - GRAYSCALE_DEPTH=1
      - COLORSPACE=Gray
      - SCALING=1
      - MONOCHROME_THRESHOLD=75%
    restart: unless-stopped
    ports:
      - 5000:5000
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:5000/ || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 60s